apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: kubernetes.io/basic-auth
data:
  username: cnVhbg==
  password: cnVhbg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: credentials
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password
        volumeMounts:
        - name: credentials
          mountPath: "/tmp"
          readOnly: true
      volumes:
        - name: credentials
          secret: 
            secretName: credentials